### ISSUE TITLE
Certificate error on website

### ISSUE THREAD

**Issue by BlackyWolf** [feathub/feathub#1]
![image](https://user-images.githubusercontent.com/16546603/39598091-0cfb866a-4edd-11e8-8424-b1f314eb3395.png)
_Edge_

![image](https://user-images.githubusercontent.com/16546603/39598136-26a6532e-4edd-11e8-87bd-862c28bd51e2.png)
_Chrome_

This is neat, however, the certificate error makes me anxious, so I don't want to use the site. Is it possible to address this some time soon?

**Comment by Ecco** [comment]
Thanks for reporting this! It's fixed!
