### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by MichaIng** [feathub/feathub#11]
https://feathub.com/ is down since at least yesterday March 5th, which is the case every now and then. Since there is zero development on FeatHub for years, despite the active FeatHub meta feature vote list, is my assumption right that the project is basically dead from that point of view?

**Comment by cocoflan** [comment]
I do thinks so. no other options for a voting system?

**Comment by MichaIng** [comment]
Plenty, including encouraging users to give 👍 👎 to the OP of a feature request on GitHub directly. But given votes cannot be migrated, so it's generally loss of votes when migrating so something else.

**Comment by MichaIng** [comment]
I'll mark this as closed as the website is up again for a while.

**Comment by Pysis868** [comment]
Again today =/:
```
> nslookup feathub.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	feathub.com
Address: 86.245.174.214

> dig +short A whoami.akamai.net
172.70.37.116

> ping -w 10 feathub.com
PING feathub.com (86.245.174.214) 56(84) bytes of data.

--- feathub.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9240ms
```

Without using the site, I assume the problems are interactivity and efficiency.  You can't see these reactions from the list page, and largely not convenient to open each issue and track the manually, either with the GUI or API, and also sort this list automatically.  The website would solve this effort for every project maintainer.
